export const users = [
  {
    id: 'user-1',
    name: 'Tanish Poddar',
    username: 'Tanishpoddar.18',
    password: 'password123', // In a real app, hash this!
    email: 'tanish.poddar@cloudx.com',
    avatar: 'https://picsum.photos/seed/tanish/100/100',
    role: 'Co-founder',
    team: 'Presidium',
    subTeam: null,
    birthday: '1998-05-18',
    phone: '+1-202-555-0178',
    linkedin: 'https://linkedin.com/in/tanishpoddar',
    github: 'https://github.com/tanishpoddar'
  },
  {
    id: 'user-2',
    name: 'Sarthak Lal',
    username: 'Sarthaklal.18',
    password: 'password123',
    email: 'sarthak.lal@cloudx.com',
    avatar: 'https://picsum.photos/seed/sarthak/100/100',
    role: 'Co-founder',
    team: 'Presidium',
    subTeam: null,
    birthday: '1999-02-11',
    phone: '+1-202-555-0112',
    linkedin: 'https://linkedin.com/in/sarthaklal',
    github: 'https://github.com/sarthaklal'
  },
  {
    id: 'user-3',
    name: 'Asmi Sharma',
    username: 'Asmisharma.18',
    password: 'password123',
    email: 'asmi.sharma@cloudx.com',
    avatar: 'https://picsum.photos/seed/asmi/100/100',
    role: 'Secretary',
    team: 'Presidium',
    subTeam: null,
    birthday: '2000-09-01',
    phone: '+1-202-555-0145',
    linkedin: 'https://linkedin.com/in/asmisharma',
    github: 'https://github.com/asmisharma'
  },
  {
    id: 'user-4',
    name: 'Sukhad Kaur',
    username: 'Sukhadkaur.18',
    password: 'password123',
    email: 'sukhad.kaur@cloudx.com',
    avatar: 'https://picsum.photos/seed/sukhad/100/100',
    role: 'Chair of Directors',
    team: 'Technology',
    subTeam: null,
    birthday: '2001-11-23',
    phone: '+1-202-555-0189',
    linkedin: 'https://linkedin.com/in/sukhadkaur',
    github: 'https://github.com/sukhadkaur'
  },
  {
    id: 'user-5',
    name: 'Kavya Singh',
    username: 'Kavyasingh.18',
    password: 'password123',
    email: 'kavya.singh@cloudx.com',
    avatar: 'https://picsum.photos/seed/kavya/100/100',
    role: 'Chair of Directors',
    team: 'Corporate',
    subTeam: null,
    birthday: '2000-07-15',
    phone: '+1-202-555-0199',
    linkedin: 'https://linkedin.com/in/kavyasingh',
    github: 'https://github.com/kavyasingh'
  },
  {
    id: 'user-6',
    name: 'Saksham Gupta',
    username: 'Sakshamgupta.18',
    password: 'password123',
    email: 'saksham.gupta@cloudx.com',
    avatar: 'https://picsum.photos/seed/saksham/100/100',
    role: 'Chair of Directors',
    team: 'Creatives',
    subTeam: null,
    birthday: '2002-01-30',
    phone: '+1-202-555-0121',
    linkedin: 'https://linkedin.com/in/sakshamgupta',
    github: 'https://github.com/sakshamgupta'
  },
  {
    id: 'user-7',
    name: 'Ananya Agrawal',
    username: 'aa6196',
    password: 'password123',
    email: 'aa6196@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/ananya/100/100',
    role: 'Lead',
    team: 'Technology',
    subTeam: 'dev',
    phone: '6260390164',
    linkedin: 'https://www.linkedin.com/in/ananya-agrawal002/',
    github: 'https://github.com/Ananya020'
  },
  {
    id: 'user-8',
    name: 'Ashwin Chakraborty',
    username: 'ac3701',
    password: 'password123',
    email: 'ac3701@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/ashwin/100/100',
    role: 'Lead',
    team: 'Technology',
    subTeam: 'aiml',
    phone: '9064208510',
    linkedin: 'https://www.linkedin.com/in/ashwinchakraborty',
    github: 'https://github.com/Ashwinzzz'
  },
  {
    id: 'user-9',
    name: 'Prabhav Singh',
    username: 'ps9681',
    password: 'password123',
    email: 'ps9681@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/prabhav/100/100',
    role: 'Lead',
    team: 'Technology',
    subTeam: 'iot',
    phone: '7309464842',
    linkedin: null,
    github: 'https://github.com/Prabhav558'
  },
  {
    id: 'user-10',
    name: 'Swapnil Chatterjee',
    username: 'Sc5821',
    password: 'password123',
    email: 'Sc5821@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/swapnil/100/100',
    role: 'Lead',
    team: 'Technology',
    subTeam: 'ui-ux',
    phone: '9098143895',
    linkedin: 'https://www.linkedin.com/in/swapnil-chatterjee-3a3a952a5',
    github: 'https://github.com/Swapnil-Dev-spec'
  },
  {
    id: 'user-11',
    name: 'Siddharth Agarwal',
    username: 'sa9174',
    password: 'password123',
    email: 'sa9174@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/siddharth/100/100',
    role: 'Lead',
    team: 'Corporate',
    subTeam: 'sponsorship',
    phone: '8745072181',
    linkedin: 'http://linkedin.com/in/siddharth-agarwal-tech',
    github: 'https://github.com/Siddharth-Tech23'
  },
  {
    id: 'user-12',
    name: 'Pranav Shukla',
    username: 'ps8421',
    password: 'password123',
    email: 'ps8421@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/pranav/100/100',
    role: 'Lead',
    team: 'Corporate',
    subTeam: 'sponsorship',
    phone: '9950640302',
    linkedin: null,
    github: null
  },
  {
    id: 'user-13',
    name: 'Anand Arora',
    username: 'aa5916',
    password: 'password123',
    email: 'aa5916@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/anand/100/100',
    role: 'Lead',
    team: 'Corporate',
    subTeam: 'events',
    phone: '7296857259',
    linkedin: 'https://www.linkedin.com/in/anandaroraii',
    github: 'https://github.com/MyridS2'
  },
  {
    id: 'user-14',
    name: 'Rohit Sunkari',
    username: 'rs1938',
    password: 'password123',
    email: 'rs1938@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/rohit/100/100',
    role: 'Lead',
    team: 'Corporate',
    subTeam: 'ops',
    phone: '7751987271',
    linkedin: 'https://www.linkedin.com/in/rohit-sunkari',
    github: 'https://github.com/rohitsunkari08'
  },
  {
    id: 'user-15',
    name: 'Kushal Kumar Jaiswal',
    username: 'kj0628',
    password: 'password123',
    email: 'kj0628@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/kushal/100/100',
    role: 'Lead',
    team: 'Corporate',
    subTeam: 'pr',
    phone: '9804288804',
    linkedin: 'https://www.linkedin.com/in/kushal-jaiswal-5117b7298',
    github: 'https://github.com/thekushaljaiswal'
  },
  {
    id: 'user-16',
    name: 'Nityanand Kumar',
    username: 'nk1706',
    password: 'password123',
    email: 'nk1706@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/nityanand/100/100',
    role: 'Lead',
    team: 'Corporate',
    subTeam: 'ops',
    phone: '6205247989',
    linkedin: null,
    github: 'https://github.com/nityaa19'
  },
  {
    id: 'user-17',
    name: 'Nidhi Nayana',
    username: 'nn1591',
    password: 'password123',
    email: 'nn1591@srmist.edu.in',
    avatar: 'https://picsum.photos/seed/nidhi/100/100',
    role: 'Lead',
    team: 'Creatives',
    subTeam: 'media',
    phone: '8709145857',
    linkedin: 'https://www.linkedin.com/in/nidhi-nayana/',
    github: 'https://github.com/nidhi-nayana'
  },
];


export const tasks = [
    {
      id: 'task-1',
      title: 'Develop new authentication module',
      description: 'Implement JWT-based authentication for the main application.',
      status: 'In Progress',
      priority: 'High',
      urgent: true,
      assignedToId: 'user-4', // Sukhad Kaur
      assignedById: 'user-1', // Tanish Poddar
      createdAt: '2024-07-20T10:00:00Z',
      dueDate: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
      files: [],
      links: [],
    },
];

export const logs = [
    {
        id: 'log-1',
        message: 'Tanish Poddar assigned "Develop new authentication module" to Sukhad Kaur.',
        timestamp: '2024-07-20T10:00:00Z',
        userId: 'user-1',
        taskId: 'task-1'
    },
];
